In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [3]:
env = gym.make("FrozenLake-v1")


/Users/jijnasu/Library/CloudStorage/OneDrive-Personal/Documents/Reinforcement Learning/deeplizard/openaiGym/lib/python3.9/site-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/Users/jijnasu/Library/CloudStorage/OneDrive-Personal/Documents/Reinforcement Learning/deeplizard/openaiGym/lib/python3.9/site-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [4]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [5]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [24]:
rewards_all_episodes = []


for episode in range(num_episodes):
    state = env.reset()

    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)


        q_table[state, action] = q_table[state, action]*(1-learning_rate) + learning_rate*(reward + discount_rate*np.max(q_table[new_state,:]))

        state = new_state
        rewards_current_episode += reward
        if done:
            break

    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate)* np.exp(-exploration_decay_rate * episode)

    rewards_all_episodes.append(rewards_current_episode)

In [25]:
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
count = 1000

print("===AVERAGE REWARD PER THOUSAND EPISODE===\n")
for r in rewards_per_thousand_episodes:
    print(count, ' : ', str(sum(r/1000)))
    count += 1000

print('\n\n===Q-Table===\n')
print(q_table)

===AVERAGE REWARD PER THOUSAND EPISODE===

1000  :  0.04900000000000004
2000  :  0.21400000000000016
3000  :  0.4050000000000003
4000  :  0.5670000000000004
5000  :  0.6210000000000004
6000  :  0.6580000000000005
7000  :  0.6850000000000005
8000  :  0.6800000000000005
9000  :  0.6460000000000005
10000  :  0.6750000000000005


===Q-Table===

[[0.55936002 0.51503565 0.51318153 0.51170144]
 [0.31257096 0.34317665 0.28603086 0.50585274]
 [0.39198714 0.40311207 0.39215514 0.47196993]
 [0.35206599 0.28161641 0.28436801 0.45188414]
 [0.58975429 0.33193408 0.43040485 0.35305975]
 [0.         0.         0.         0.        ]
 [0.31990334 0.07939731 0.1829747  0.15836253]
 [0.         0.         0.         0.        ]
 [0.32413466 0.37479745 0.31785584 0.62267007]
 [0.57460414 0.66140552 0.47738751 0.3410247 ]
 [0.65186708 0.40413539 0.41505486 0.3121462 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.4803081  0.62153719 0.79907235 0.58757495]